export const urduToRomanMap: Record<string, string> = {
  "ا": "a",
  "آ": "aa",
  "ع": "a",
  "ء": "",
  "و": "o",
  "ی": "i",
  "ے": "e",
  "ب": "b",
  "پ": "p",
  "ت": "t",
  "ٹ": "t",
  "ث": "s",
  "ج": "j",
  "چ": "ch",
  "ح": "h",
  "خ": "kh",
  "د": "d",
  "ڈ": "d",
  "ذ": "z",
  "ر": "r",
  "ڑ": "r",
  "ز": "z",
  "س": "s",
  "ش": "sh",
  "ص": "s",
  "ض": "z",
  "ط": "t",
  "ظ": "z",
  "غ": "gh",
  "ف": "f",
  "ق": "q",
  "ک": "k",
  "گ": "g",
  "ل": "l",
  "م": "m",
  "ن": "n",
  "ں": "n",
  "ہ": "h",
};








export const wordPriorityMap: Record<string, string> = {
  "ہے": "hai",
  "ہوں": "hoon",
  "ہیں": "hain",
  "تھا": "tha",
  "تھی": "thi",
  "تھے": "the",
  "میں": "mein",
  "ہم": "hum",
  "وہ": "woh",
  "یہ": "yeh",
  "آپ": "aap",
  "تو": "to",
  "ہی": "hi",
  "کا": "ka",
  "کی": "ki",
  "کے": "ke",
  "سے": "se",
  "پر": "par",
  "کو": "ko",
  "اللہ": "Allah",
  "محمد": "Muhammad",
  "رسول": "Rasool",
  "نبی": "Nabi",
  "قرآن": "Quran",
  "حدیث": "Hadith",
  "اسلام": "Islam",
  "مسلمان": "Muslim",
  "ایمان": "Iman",
  "نماز": "Namaz",
  "روزہ": "Roza",
  "زکوٰۃ": "Zakat",
  "حج": "Hajj",
  "صدقہ": "Sadaqah",
  "جنت": "Jannat",
  "دوزخ": "Dozakh",
  "آخرت": "Aakhirat",
  "شریعت": "Shariat",
  "فقہ": "Fiqh",
  "اجماع": "Ijma",
  "قیامت": "Qayamat",
  "الحمد للہ": "Alhamdulillah",
  "ان شاء اللہ": "InshaAllah",
  "ما شاء اللہ": "MashaAllah",
  "جزاک اللہ": "JazakAllah",
  "اللہ اکبر": "Allahu Akbar",
  "السلام علیکم": "Assalamu Alaikum",
  "وعلیکم السلام": "Wa Alaikum Assalam",
  "رحمت اللہ": "Rahmatullah",
  "برکاتہ": "Barakatuh",
  "حسن": "Hasan",
  "حسین": "Husain",
  "علی": "Ali",
  "فاطمہ": "Fatima",
  "عائشہ": "Aisha",
  "عمر": "Umar",
  "عثمان": "Usman",
  "ابوبکر": "Abu Bakr",
};
